public class LeadProcessorCopy implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator(
            'SELECT Id, LeadSource FROM Lead'
        );
    }

    public void execute(Database.BatchableContext bc, List<Lead> scope) {

        for(Lead l : scope) {
            l.LeadSource = 'Dreamforce';
        }

        update scope;
    }

    public void finish(Database.BatchableContext bc) {

    }
}